language: go

go:
- 1.11.x
- 1.12.x

env:
  global:
  - GO111MODULE=on

cache:
  directories:
  - /go/pkg/mod/cache

before_install:
- go get -u golang.org/x/lint/golint

install:
- go mod download

script:
- make ci-test

after_success:
- bash <(curl -s https://codecov.io/bash)
